services: 
  mysql: 
    image: mysql:latest
    container_name: mysql_database_wisechain
    environment: 
      MYSQL_ROOT_PASSWORD: Motdepasse123@
    ports: 
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    restart: always
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_wisechain
    ports:
      - "9090:80"
    links:
      - mysql:db
    restart: always

volumes: 
  database:
    external: true
    name: mysql_data